config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'

  resources :promotions do
    member do
      post 'generate_coupons'
      post 'approve'
    end
    get 'search', on: :collection
  end

  resources :coupons, only: [:show] do
    member do
      post 'disable'
      post 'activate'
    end
    get 'search', on: :collection
  end

  resources :product_categories

  namespace :api, constraints: ->(req) { req.format == :json } do
    namespace :v1 do
      resources :coupons, only: [:show], param: :code
      resources :product_categories, only: [:show, :create, :update, :destroy], param: :code
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coupon.rb
class Coupon < ApplicationRecord
  belongs_to :promotion

  enum status: { active: 0, disabled: 10 }

  delegate :discount_rate, to: :promotion
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  validates :name, :code, presence: true
  validates :code, :name, uniqueness: true

  has_many :promotion_product_categories, dependent: :restrict_with_error
  has_many :promotions, through: :promotions_product_categories
end

app/models/promotion.rb
class Promotion < ApplicationRecord
  belongs_to :user
  has_many :coupons, dependent: :restrict_with_error
  has_many :promotion_product_categories, dependent: :restrict_with_error
  has_many :product_categories, through: :promotion_product_categories
  has_one :promotion_approval, dependent: :destroy
  has_one :approver, through: :promotion_approval, source: :user

  validates :name, :code, :discount_rate, :coupon_quantity,
            :expiration_date, presence: true
  validates :code, :name, uniqueness: true

  def generate_coupons!
    return if coupons?

    Coupon.transaction do
      (1..coupon_quantity).each do |number|
        coupons.create!(code: "#{code}-#{format('%04d', number)}")
      end
    end
  end

  def coupons?
    coupons.any?
  end

  def self.search(query)
    where('name LIKE ?', "%#{query}%")
  end

  def approved?
    promotion_approval.present?
  end

  def can_approve?(current_user)
    user != current_user
  end

  def generate_promotion_product_categories!(product_categories_ids)
    promotion_product_categories.destroy_all
    product_categories_ids.each do |product_category_id|
      product_category = ProductCategory.find(product_category_id) if product_category_id.present?
      PromotionProductCategory.create!(product_category: product_category, promotion: self) if product_category.present?
    end
  end
end

app/models/promotion_approval.rb
class PromotionApproval < ApplicationRecord
  belongs_to :promotion
  belongs_to :user
end

app/models/promotion_product_category.rb
class PromotionProductCategory < ApplicationRecord
  belongs_to :promotion
  belongs_to :product_category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :promotions, dependent: :destroy
  has_many :promotion_approvals, dependent: :nullify
  has_many :approved_promotions, through: :promotion_approvals, source: :promotion
end

app/controllers/api/v1/api_controller.rb
class Api::V1::ApiController < ActionController::API
  respond_to :json
  rescue_from ActiveRecord::RecordNotFound, with: :not_found_error
  rescue_from ActiveRecord::RecordInvalid, with: :invalid_error

  private

  def not_found_error
    head 404
  end

  def invalid_error(exception)
    render json: { errors: exception }, status: :unprocessable_entity
  end
end

app/controllers/api/v1/coupons_controller.rb
class Api::V1::CouponsController < Api::V1::ApiController
  def show
    @coupon = Coupon.find_by!(code: params[:code])
  end
end

app/controllers/api/v1/product_categories_controller.rb
class Api::V1::ProductCategoriesController < Api::V1::ApiController
  before_action :set_product_category, only: %i[show update destroy]
  before_action :product_category_params, only: %i[create update]

  def show; end

  def create
    @product_category = ProductCategory.create!(product_category_params)
  end

  def update
    @product_category.update(product_category_params)
  end

  def destroy
    @product_category.destroy!
  end

  private

  def set_product_category
    @product_category = ProductCategory.find_by(code: params[:code])
  end

  def product_category_params
    params.require(:product_category).permit(:name, :code)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/coupons_controller.rb
class CouponsController < ApplicationController
  before_action :set_coupon, only: %i[show disable activate]
  before_action :search_by_code, only: %i[search]

  def show; end

  def disable
    @coupon.disabled!
    redirect_to @coupon.promotion, notice: t('.success', code: @coupon.code)
  end

  def activate
    @coupon.active!
    redirect_to @coupon.promotion, notice: 'Cupom NATAL10-0001 ativado com sucesso'
  end

  def search
    redirect_to @coupon
  end

  private

  def set_coupon
    @coupon = Coupon.find(params[:id])
  end

  def search_by_code
    @coupon = Coupon.find_by(code: params[:code])
    redirect_back fallback_location: :fallback_location, notice: 'Cupom não encontrado' unless @coupon
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/product_categories_controller.rb
class ProductCategoriesController < ApplicationController
  before_action :set_product_category, only: %i[show edit update destroy]

  def index
    @product_categories = ProductCategory.all
  end

  def show; end

  def new
    @product_category = ProductCategory.new
  end

  def create
    @product_category = ProductCategory.new(product_category_params)
    if @product_category.save
      redirect_to @product_category
    else
      render :new
    end
  end

  def edit; end

  def update
    @product_category.update(product_category_params)
    redirect_to root_path
  end

  def destroy
    @product_category.destroy
    redirect_to product_categories_path
  end

  private

  def set_product_category
    @product_category = ProductCategory.find(params[:id])
  end

  def product_category_params
    params.require(:product_category).permit(:name, :code)
  end
end

app/controllers/promotions_controller.rb
class PromotionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_promotion, only: %i[show edit update destroy generate_coupons approve]
  before_action :can_be_approved, only: %i[approve]

  def index
    @promotions = Promotion.all
  end

  def show; end

  def new
    @promotion = Promotion.new
  end

  def create
    @promotion = current_user.promotions.new(promotion_params)
    if @promotion.save
      @promotion.generate_promotion_product_categories!(promotion_product_categories_params)
      redirect_to @promotion
    else
      render :new
    end
  end

  def edit
    @generated_coupons = @promotion.coupons?
    @promotion_product_categories = @promotion.promotion_product_categories.all
  end

  def update
    @promotion.update(promotion_params)
    @promotion.generate_promotion_product_categories!(promotion_product_categories_params)
    redirect_to promotions_path
  end

  def destroy
    @promotion.destroy
    redirect_to promotions_path
  end

  def generate_coupons
    @promotion.generate_coupons!
    redirect_to @promotion, notice: t('.success')
  end

  def search
    @promotions = Promotion.search(params[:q])
  end

  def approve
    current_user.promotion_approvals.create!(promotion: @promotion)
    PromotionMailer
      .with(promotion: @promotion, approver: current_user)
      .approval_email
      .deliver_now
    redirect_to @promotion, notice: 'Promoção aprovada com sucesso'
  end

  private

  def set_promotion
    @promotion = Promotion.find(params[:id])
  end

  def promotion_params
    params
      .require(:promotion)
      .permit(:name, :description, :expiration_date,
              :code, :discount_rate, :coupon_quantity)
  end

  def promotion_product_categories_params
    params
      .require(:promotion)
      .require(:product_category_ids)
  end

  def can_be_approved
    redirect_to @promotion, alert: 'Ação não permitida' unless @promotion.can_approve?(current_user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/coupons/show.html.erb
<h3><%= @coupon.code %></h3>
<dl>
  <dt><%= Coupon.human_attribute_name(:status) %></dt>
  <dd><%= Coupon.human_attribute_name("status.#{@coupon.status}").camelize %></dd>
  <dt><%= Promotion.model_name.human %></dt>
  <dd><%= @coupon.promotion.name %></dd>
  <dt><%= Promotion.human_attribute_name(:description) %></dt>
  <dd><%= @coupon.promotion.description %></dd>
  <dt><%= Promotion.human_attribute_name(:discount_rate) %></dt>
  <dd><%= number_to_percentage @coupon.promotion.discount_rate, precision: 2 %></dd>
  <dt><%= Promotion.human_attribute_name(:expiration_date) %></dt>
  <dd><%= l @coupon.promotion.expiration_date %></dd>
</dl>

app/views/home/index.html.erb
<h1>Promotion System</h1>
<h3>Boas vindas ao sistema de gestão de promoções</h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sistema de Promoções</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-dark bg-dark">
      <div class="container-fluid">
        <%= link_to 'Sistema de Promoções', root_path, class: 'navbar-brand' %>
        <%# <div class="collapse navbar-collapse" id="navbarSupportedContent"> %>
          <ul class="nav justify-content-end">
            <% if user_signed_in? %>
              <%= render partial: 'shared/logged_menu'%>
            <% else %>
              <%= render partial: 'shared/not_logged_menu'%>
            <% end %>
          </ul>
        <%# </div> %>
      </div>
    </nav>
    <div class='container mb-4'>
      <p><%= flash[:notice] %></p>
      <p><%= flash[:alert] %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/product_categories/_form.html.erb
<% if @product_category.errors.any? %>
  <ul>
    <% @product_category.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>


<%= form_with model: @product_category do |f| %>
  <div class="mb-3">
    <%= f.label :name, class: 'form-label' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="mb-3">
    <%= f.label :code, class: 'form-label' %>
    <%= f.text_field :code, class: 'form-control' %>
  </div>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/product_categories/edit.html.erb
<h1>Editar uma categoria de produto</h1>

<%= render partial: "form", locals: { product_category: @product_category  } %>

app/views/product_categories/index.html.erb
<div class="d-flex justify-content-between mb-3">
  <%= link_to 'Voltar', root_path %>
  <%= link_to 'Registrar uma categoria de produto', new_product_category_path %>
</div>


<% if @product_categories.any? %>
  <table class="table table-striped table-hover last-2-colluns-right">
    <tr class="table-dark">
      <th><%= ProductCategory.human_attribute_name(:name) %></th>
      <th><%= ProductCategory.human_attribute_name(:code) %></th>
      <th></th>
      <th></th>
    </tr>

    <% @product_categories.each do |product_category| %>
      <tr id="product-category-<%= product_category.code.parameterize %>">
        <td><%= link_to product_category.name, product_category %></td>
        <td><%= product_category.code %></td>
        <td><%= link_to 'Editar', edit_product_category_path(product_category) %></td>
        <td>
          <%= link_to 'Deletar', product_category_path(product_category), method: :delete,
            data: { confirm: 'Quer apagar esta categoria de produto?'} %>
        </td>
      </tr>
    <% end %>
    </table>
<% end %>

<% if @product_categories.empty? %>
  <h3>Nenhuma categoria de produto cadastrada</h3>
<% end %>

app/views/product_categories/new.html.erb
<h1>Registrar uma categoria de produto</h1>

<%= render partial: "form", locals: { product_category: @product_category } %>

app/views/product_categories/show.html.erb
<%= link_to 'Voltar', product_categories_path %>

<dl>
  <dd><%= ProductCategory.human_attribute_name(:name) %></dd>
  <dt><%= @product_category.name %></dt>
  <dd><%= ProductCategory.human_attribute_name(:code) %></dd>
  <dt><%= @product_category.code %></dt>
</dl>

app/views/promotions/_details.html.erb
<div class="d-flex justify-content-between">
  <%= link_to 'Voltar', root_path %>
  <%= link_to 'Registrar uma promoção', new_promotion_path, class: 'text-end' %>
</div>

<% if show_search %>
  <div class="float-end mb-3">
    <%= form_with url: search_promotions_path, method: :get do |f| %>
      <%= f.label :q, 'Busca'%>
      <%= f.text_field :q%>
      <%= f.submit 'Buscar'%>
    <% end %>
  </div>
<% end %>

<% if promotions.any? %>
  <table class="table table-striped table-hover last-2-colluns-right">
    <tr class="table-dark">
      <th><%= Promotion.human_attribute_name(:name) %></th>
      <th><%= Promotion.human_attribute_name(:description) %></th>
      <th><%= Promotion.human_attribute_name(:discount_rate) %></th>
      <th></th>
      <th></th>
    </tr>
    <% promotions.each do |promotion| %>
      <tr id="promotion-<%= promotion.code.parameterize %>">
        <td><%= link_to promotion.name, promotion %></td>
        <td><%= promotion.description %></td>
        <td><%= number_to_percentage promotion.discount_rate, precision: 2 %></td>
        <td><%= link_to 'Editar', edit_promotion_path(promotion) %></td>
        <td>
          <%= link_to 'Deletar', promotion_path(promotion), method: :delete,
              data: { confirm: 'Quer apagar esta promoção?'} %>
        </td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/promotions/_form.html.erb
<% if @promotion.errors.any? %>
  <ul>
    <% @promotion.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @promotion do |f| %>
  <div class="mb-3">
    <%= f.label :name, class: 'form-label' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="mb-3">
    <%= f.label :description, class: 'form-label' %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="mb-3">
    <%= f.label :code, class: 'form-label' %>
    <%= f.text_field :code, disabled: generated_coupons, class: 'form-control' %>
  </div>
  <div class="mb-3">
    <%= f.label :discount_rate, class: 'form-label' %>
    <%= f.number_field :discount_rate, in: 0..100, step: 0.01, disabled: generated_coupons, class: 'form-control' %>
  </div>
  <div class="mb-3">
    <%= f.label :coupon_quantity, class: 'form-label' %>
    <%= f.number_field :coupon_quantity, min: 1, disabled: generated_coupons, class: 'form-control' %>
  </div>
  <div class="mb-3">
    <%= f.label :expiration_date, class: 'form-label' %>
    <%= f.date_field :expiration_date, disabled: generated_coupons, class: 'form-control' %>
  </div>
  <div class="mb-3">
    <%= f.collection_check_boxes :product_category_ids, ProductCategory.all, :id, :name %>
  </div>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/promotions/edit.html.erb
<h1>Editar uma promoção</h1>

<%= render partial: "form", locals: { promotion: @promotion,
                                      promotion_product_categories: @promotion_product_categories,
                                      generated_coupons: @generated_coupons } %>

app/views/promotions/index.html.erb
<%= render partial: 'details', locals: { promotions: @promotions, show_search: @promotions.any? } %>

<% if @promotions.empty? %>
  <h3>Nenhuma promoção cadastrada</h3>
<% end %>

app/views/promotions/new.html.erb
<h1>Registrar uma promoção</h1>

<%= render partial: "form", locals: { promotion: @promotion,
                                      generated_coupons: false } %>

app/views/promotions/search.html.erb
<%= render partial: 'details', locals: { promotions: @promotions, show_search: true } %>

<% if @promotions.empty? %>
  <h3>Não foram localizadas promoções para esta busca</h3>
<% end %>

app/views/promotions/show.html.erb
<%= link_to t('buttons.back'), promotions_path %>

<h3><%= @promotion.name %></h3>
<dl>
  <dt><%= Promotion.human_attribute_name(:description) %></dt>
  <dd><%= @promotion.description %></dd>
  <dt><%= Promotion.human_attribute_name(:discount_rate) %> <small>em porcentagem</small></dt>
  <dd><%= number_to_percentage @promotion.discount_rate, precision: 2 %></dd>
  <dt><%= Promotion.human_attribute_name(:code) %></dt>
  <dd><%= @promotion.code %></dd>
  <dt><%= Promotion.human_attribute_name(:expiration_date) %></dt>
  <dd><%= l @promotion.expiration_date %></dd>
  <dt><%= Promotion.human_attribute_name(:coupon_quantity) %></dt>
  <dd><%= @promotion.coupon_quantity %></dd>
</dl>

<% if @promotion.approved? %>
  <p>Aprovada por: <%= @promotion.approver.email %></p>
  <% if @promotion.coupons.empty? %>
    <%= link_to t('.generate_coupons'), generate_coupons_promotion_path(@promotion), method: :post %>
  <% end %>
<% elsif @promotion.can_approve?(current_user) %>
  <%= link_to 'Aprovar', approve_promotion_path(@promotion), method: :post, data: { confirm: 'Tem certeza? Essa operação não pode ser desfeita' }%>
<% end %>

<% if @promotion.promotion_product_categories.any? %>
  <div class="container">
    <strong>Permitido para as Categorias de Produtos:</strong>
    <ul>
      <% @promotion.promotion_product_categories.each do |promotion_product_category| %>
        <li><%= promotion_product_category.product_category.name %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<% @promotion.coupons.each do |coupon| %>
  <div id="coupon-<%= coupon.code.parameterize %>">
    <p>
      <%= coupon.code %>
      <% if coupon.disabled? %>
        (<%= Coupon.human_attribute_name("status.#{coupon.status}")%>)
        <%= link_to 'Ativar', activate_coupon_path(coupon), method: :post, data: { disable_with: 'Estamos ativando...' } %>
      <% else %>
        <%= link_to 'Desabilitar', disable_coupon_path(coupon), method: :post, data: { disable_with: 'Estamos desabilitando...' } %>
      <% end %>
    </p>
  </div>
<% end %>

app/views/shared/_coupon_search_modal.html.erb
<div class="modal fade" id="couponModal" tabindex="-1" aria-labelledby="couponModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="couponModalLabel">Pesquisa de Cupom</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= form_with url: search_coupons_path, method: :get do |f| %>
          <%= f.label :code, 'Código'%>
          <%= f.text_field :code%>
          <%= f.submit 'Buscar'%>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_logged_menu.html.erb
<li class="nav-item">
  <%= link_to current_user.email, '#', class: 'nav-link disabled' %>
</li>
<li class="nav-item">
  <%= link_to 'Promoções', promotions_path, class: 'nav-link' %>
</li>
<li class="nav-item">
  <a href="#couponModal" data-bs-toggle="modal" data-target="#couponModal" class="nav-link active">Buscar Cupom</a>
</li>
<li class="nav-item">
  <%= link_to 'Categorias de Produtos', product_categories_path, class: 'nav-link active' %>
</li>
<li class="nav-item">
  <%= link_to 'Sair', destroy_user_session_path, method: :delete, class: 'nav-link active' %>
</li>

<%= render partial: 'shared/coupon_search_modal' %>

app/views/shared/_not_logged_menu.html.erb
<li class="nav-item" id="nav-sign-up">
  <%= link_to 'Cadastrar', new_user_registration_path, class: 'nav-link active' %>
</li>
<li class="nav-item" id="nav-sign-in">
  <%= link_to 'Entrar', new_user_session_path, class: 'nav-link active' %>
</li>